/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib_admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mib_verktyg.Validering;
import mib_verktyg.Alien;

public class AdminUppdateraAlien extends javax.swing.JFrame {

    public AdminUppdateraAlien() {
        initComponents();
        this.setLocationRelativeTo(null);
        visa_alien();
        alienbytetxt.setEnabled(false);
    }

    public ArrayList<Alien> alienList() {
        ArrayList<Alien> aliensList = new ArrayList<>();

        try {
            String sql = "SELECT * FROM alien";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            Alien alien;
            while (rs.next()) {
                alien = new Alien(rs.getInt("Alien_ID"), rs.getInt("Plats"), rs.getInt("Ansvarig_Agent"), rs.getString("Registreringsdatum"), rs.getString("Losenord"), rs.getString("Namn"), rs.getString("Telefon"));
                aliensList.add(alien);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return aliensList;
    }

    public void visa_alien() {
        ArrayList<Alien> list = alienList();
        DefaultTableModel model = (DefaultTableModel) visaValdRadTabellAdmin.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getalienid();
            row[1] = list.get(i).getregistreringsdatum();
            row[2] = list.get(i).getlosenord();
            row[3] = list.get(i).getnamn();
            row[4] = list.get(i).gettelefon();
            row[5] = list.get(i).getplats();
            row[6] = list.get(i).getansvarigagent();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        ansbytetxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        platsbytetxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        telebytetxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        updbytebtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        alienbytetxt = new javax.swing.JTextField();
        Namnbytetxt = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        losenordbytetxt = new javax.swing.JTextField();
        adminuppdateratillbakatbn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regdatumbytetxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rasbox1 = new javax.swing.JComboBox<>();
        rastext1 = new javax.swing.JLabel();
        antaltxt1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        visaValdRadTabellAdmin = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        rasantaltable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel21.setText("Ansvarig agent-ID:");

        ansbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansbytetxtActionPerformed(evt);
            }
        });

        jLabel22.setText("Plats ID:");

        jLabel23.setText("Telefonnummer:");

        jLabel19.setText("Alien ID");

        updbytebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updbytebtn.setText("Uppdatera");
        updbytebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbytebtnActionPerformed(evt);
            }
        });

        jLabel20.setText("Namn:");

        Namnbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamnbytetxtActionPerformed(evt);
            }
        });

        txt.setText("Lösenord:");

        adminuppdateratillbakatbn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        adminuppdateratillbakatbn.setText("Tillbaka");
        adminuppdateratillbakatbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuppdateratillbakatbnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Uppdatera alien");

        regdatumbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdatumbytetxtActionPerformed(evt);
            }
        });

        jLabel24.setText("Registreringsdatum:");

        rasbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj ras", "Boglodite", "Squid", "Worm" }));
        rasbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasbox1ActionPerformed(evt);
            }
        });

        antaltxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antaltxt1ActionPerformed(evt);
            }
        });

        visaValdRadTabellAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alien ID", "Datum", "Losenord", "Namn", "Telefon", "Plats", "Ansvarig"
            }
        ));
        visaValdRadTabellAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visaValdRadTabellAdminMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(visaValdRadTabellAdmin);

        rasantaltable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ras", "Antal boogies"
            }
        ));
        jScrollPane9.setViewportView(rasantaltable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel1)
                                    .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(regdatumbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(platsbytetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addComponent(telebytetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(losenordbytetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Namnbytetxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(adminuppdateratillbakatbn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(rasbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rastext1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(antaltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(updbytebtn)
                                    .addGap(55, 55, 55)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ansbytetxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminuppdateratillbakatbn)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regdatumbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(losenordbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Namnbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telebytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platsbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ansbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rastext1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antaltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rasbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updbytebtn)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updbytebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbytebtnActionPerformed
        if (Validering.textFaltHarVarde(Namnbytetxt) && Validering.textFaltHarVarde(regdatumbytetxt) && Validering.giltigtDatum(regdatumbytetxt) && Validering.textFaltHarVarde(losenordbytetxt) && Validering.textFaltHarVarde(ansbytetxt) && Validering.isHeltal(ansbytetxt) && Validering.textFaltHarVarde(platsbytetxt) && Validering.isHeltal(platsbytetxt) && Validering.textFaltHarVarde(telebytetxt) && Validering.textFaltHarVarde(alienbytetxt) && Validering.isHeltal(alienbytetxt)) {
            try {
                String sql = "UPDATE alien SET Namn=?, Registreringsdatum=?, Losenord=?, Ansvarig_Agent=?, Plats=?, Telefon=? WHERE Alien_ID=?";
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, Namnbytetxt.getText());
                pst.setString(2, regdatumbytetxt.getText());
                pst.setString(3, losenordbytetxt.getText());
                pst.setString(4, ansbytetxt.getText());
                pst.setString(5, platsbytetxt.getText());
                pst.setString(6, telebytetxt.getText());
                pst.setString(7, alienbytetxt.getText());
                pst.executeUpdate();
                if (rasbox1.getSelectedItem().equals("Boglodite")) {
                    String sql0 = "DELETE FROM boglodite WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql0);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql1 = "INSERT INTO boglodite (Alien_ID, Antal_Boogies) VALUES (?, ?)";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql1);
                    pst.setString(1, alienbytetxt.getText());
                    pst.setString(2, antaltxt1.getText());
                    pst.executeUpdate();
                    String sql2 = "DELETE FROM squid WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql2);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql3 = "DELETE FROM worm WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql3);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                }
                if (rasbox1.getSelectedItem().equals("Squid")) {
                    String sql0 = "DELETE FROM squid WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql0);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql1 = "INSERT INTO squid (Alien_ID, Antal_Armar) VALUES (?, ?)";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql1);
                    pst.setString(1, alienbytetxt.getText());
                    pst.setString(2, antaltxt1.getText());
                    pst.executeUpdate();
                    String sql2 = "DELETE FROM boglodite WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql2);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql3 = "DELETE FROM worm WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql3);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                }
                if (rasbox1.getSelectedItem().equals("Worm")) {
                    String sql0 = "DELETE FROM worm WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql0);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql1 = "INSERT INTO worm (Alien_ID) VALUES (?)";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql1);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql2 = "DELETE FROM squid WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql2);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                    String sql3 = "DELETE FROM boglodite WHERE Alien_ID=?";
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                    pst = con.prepareStatement(sql3);
                    pst.setString(1, alienbytetxt.getText());
                    pst.executeUpdate();
                }
                JOptionPane.showMessageDialog(null, "Uppdaterad alien");
                DefaultTableModel model = (DefaultTableModel) visaValdRadTabellAdmin.getModel();
                model.setRowCount(0);
                DefaultTableModel model2 = (DefaultTableModel) rasantaltable2.getModel();
                model2.setRowCount(0);
                visa_alien();
                AdminAlienInfo meny = new AdminAlienInfo();
                meny.setVisible(true);
                setVisible(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Vald alien/kolumn existerar ej!");
            }
        }
    }//GEN-LAST:event_updbytebtnActionPerformed

    private void NamnbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamnbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamnbytetxtActionPerformed

    private void adminuppdateratillbakatbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuppdateratillbakatbnActionPerformed
        AdminAlienInfo meny = new AdminAlienInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminuppdateratillbakatbnActionPerformed

    private void regdatumbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdatumbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regdatumbytetxtActionPerformed

    private void rasbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasbox1ActionPerformed
        if (rasbox1.getSelectedItem().equals("Boglodite")) {
            antaltxt1.setText("");
            antaltxt1.setEnabled(true);
            rastext1.setText("Antal boogies:");
        } else if (rasbox1.getSelectedItem().equals("Squid")) {
            antaltxt1.setText("");
            antaltxt1.setEnabled(true);
            rastext1.setText("Antal armar:");
        } else if (rasbox1.getSelectedItem().equals("Worm")) {
            antaltxt1.setEnabled(false);
            rastext1.setText("Vald ras:");
            antaltxt1.setText("Worm");
        }
        //Här görs en if else if sats, om vald ruta väljs i combo boxen så kommer villkoren för den valda att synas.
    }//GEN-LAST:event_rasbox1ActionPerformed

    private void antaltxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antaltxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antaltxt1ActionPerformed

    private void ansbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansbytetxtActionPerformed

    private void visaValdRadTabellAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visaValdRadTabellAdminMouseClicked
        int i = visaValdRadTabellAdmin.getSelectedRow();
        TableModel model = visaValdRadTabellAdmin.getModel();
        alienbytetxt.setText(model.getValueAt(i, 0).toString());
        regdatumbytetxt.setText(model.getValueAt(i, 1).toString());
        losenordbytetxt.setText(model.getValueAt(i, 2).toString());
        Namnbytetxt.setText(model.getValueAt(i, 3).toString());
        telebytetxt.setText(model.getValueAt(i, 4).toString());
        platsbytetxt.setText(model.getValueAt(i, 5).toString());
        ansbytetxt.setText(model.getValueAt(i, 6).toString());
        rasantaltable2.setModel(new DefaultTableModel(null, new String[]{"Ras", "Antal boogies:"}));
        try {
            String sql = "SELECT boglodite.Antal_Boogies FROM alien JOIN boglodite ON alien.Alien_ID = boglodite.Alien_ID WHERE alien.Alien_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, alienbytetxt.getText());
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String antal = rs.getString("boglodite.Antal_Boogies");
                String tbData[] = {"Boglodite", antal};
                DefaultTableModel tblModel = (DefaultTableModel) rasantaltable2.getModel();
                tblModel.addRow(tbData);
            }
            String sql1 = "SELECT squid.Antal_Armar FROM alien JOIN squid ON alien.Alien_ID = squid.Alien_ID WHERE alien.Alien_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
            pst = con.prepareStatement(sql1);
            pst.setString(1, alienbytetxt.getText());
            ResultSet rs1 = pst.executeQuery();
            while (rs1.next()) {
                rasantaltable2.setModel(new DefaultTableModel(null, new String[]{"Ras", "Antal armar:"}));
                String antal = rs1.getString("squid.Antal_Armar");
                String tbData[] = {"Squid", antal};
                DefaultTableModel tblModel = (DefaultTableModel) rasantaltable2.getModel();
                tblModel.addRow(tbData);
            }
            String sql2 = "SELECT * FROM alien JOIN worm ON alien.Alien_ID = worm.Alien_ID WHERE alien.Alien_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
            pst = con.prepareStatement(sql2);
            pst.setString(1, alienbytetxt.getText());
            ResultSet rs2 = pst.executeQuery();
            while (rs2.next()) {
                rasantaltable2.setModel(new DefaultTableModel(null, new String[]{"Ras"}));
                String tbData[] = {"Worm"};
                DefaultTableModel tblModel = (DefaultTableModel) rasantaltable2.getModel();
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_visaValdRadTabellAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUppdateraAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Namnbytetxt;
    private javax.swing.JButton adminuppdateratillbakatbn;
    private javax.swing.JTextField alienbytetxt;
    private javax.swing.JTextField ansbytetxt;
    private javax.swing.JTextField antaltxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField losenordbytetxt;
    private javax.swing.JTextField platsbytetxt;
    private javax.swing.JTable rasantaltable2;
    private javax.swing.JComboBox<String> rasbox1;
    private javax.swing.JLabel rastext1;
    private javax.swing.JTextField regdatumbytetxt;
    private javax.swing.JTextField telebytetxt;
    private javax.swing.JLabel txt;
    private javax.swing.JButton updbytebtn;
    private javax.swing.JTable visaValdRadTabellAdmin;
    // End of variables declaration//GEN-END:variables
}
