/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib_admin;

import mib_admin.AdminAgentInfo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import mib_verktyg.Validering;
import oru.inf.InfDB;

/**
 *
 * @author Pc
 */
public class AdminAgentData extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement awp = null;
    ResultSet rs = null;
    private static InfDB idb;

    /**
     * Creates new form AdminAgentData
     */
    public AdminAgentData() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        agenttable = new javax.swing.JTable();
        jLabel36 = new javax.swing.JLabel();
        dataaidtxt = new javax.swing.JTextField();
        hamtaagentdatabtn = new javax.swing.JButton();
        adminagentdataavslutabtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "Telefon", "Anställningsdatum", "Administrator", "Lösenord", "Område"
            }
        ));
        jScrollPane1.setViewportView(agenttable);

        jLabel36.setText("Agent ID");

        hamtaagentdatabtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hamtaagentdatabtn.setText("Hämta data");
        hamtaagentdatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamtaagentdatabtnActionPerformed(evt);
            }
        });

        adminagentdataavslutabtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        adminagentdataavslutabtn.setText("Tillbaka");
        adminagentdataavslutabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminagentdataavslutabtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Agent info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminagentdataavslutabtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dataaidtxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hamtaagentdatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminagentdataavslutabtn)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hamtaagentdatabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hamtaagentdatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamtaagentdatabtnActionPerformed
        agenttable.setModel(new DefaultTableModel(null, new String[]{"Namn", "Telefon", "Anstallningsdatum", "Administrator", "Losenord", "Omrade"}));
        if (Validering.textFaltHarVarde(dataaidtxt) && Validering.isHeltal(dataaidtxt)) {
            try {
                String sql = "SELECT Namn, Telefon, Anstallningsdatum, Administrator, Losenord, Benamning FROM agent JOIN omrade ON agent.Omrade = omrade.Omrades_ID WHERE Agent_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                pst = con.prepareStatement(sql);
                pst.setString(1, dataaidtxt.getText());
                ResultSet rs = pst.executeQuery();

                while (rs.next()) {
                    String namn = rs.getString("Namn");
                    String tele = rs.getString("Telefon");
                    String ansdatum = rs.getString("Anstallningsdatum");
                    String admin = rs.getString("Administrator");
                    String losenord = rs.getString("Losenord");
                    String omrade = rs.getString("Benamning");

                    String tbData[] = {namn, tele, ansdatum, admin, losenord, omrade};
                    DefaultTableModel tblModel = (DefaultTableModel) agenttable.getModel();

                    tblModel.addRow(tbData);
                }

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_hamtaagentdatabtnActionPerformed

    private void adminagentdataavslutabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminagentdataavslutabtnActionPerformed
        AdminAgentInfo meny = new AdminAgentInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminagentdataavslutabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAgentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAgentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAgentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAgentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAgentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminagentdataavslutabtn;
    private javax.swing.JTable agenttable;
    private javax.swing.JTextField dataaidtxt;
    private javax.swing.JButton hamtaagentdatabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
