/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;


/**
 *
 * @author Pc
 */
public class AdminUppdateraAlien extends javax.swing.JFrame {

    /**
     * Creates new form AdminUppdateraAlien
     */
    public AdminUppdateraAlien() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        ansbytetxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        platsbytetxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        telebytetxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        updbytebtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        alienbytetxt = new javax.swing.JTextField();
        Namnbytetxt = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        losenordbytetxt = new javax.swing.JTextField();
        adminuppdateratillbakatbn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        regdatumbytetxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rasbox1 = new javax.swing.JComboBox<>();
        rastext1 = new javax.swing.JLabel();
        antaltxt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel21.setText("Ansvarig agent:");

        jLabel22.setText("Plats ID:");

        jLabel23.setText("Telefonnummer:");

        jLabel19.setText("Alien ID");

        updbytebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updbytebtn.setText("Uppdatera");
        updbytebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbytebtnActionPerformed(evt);
            }
        });

        jLabel20.setText("Namn:");

        Namnbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamnbytetxtActionPerformed(evt);
            }
        });

        txt.setText("Lösenord:");

        adminuppdateratillbakatbn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        adminuppdateratillbakatbn.setText("Tillbaka");
        adminuppdateratillbakatbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuppdateratillbakatbnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Uppdatera alien");

        regdatumbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdatumbytetxtActionPerformed(evt);
            }
        });

        jLabel24.setText("Registreringsdatum:");

        rasbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj ras", "Boglodite", "Squid", "Worm" }));
        rasbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasbox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adminuppdateratillbakatbn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Namnbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt)
                                .addComponent(losenordbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ansbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(platsbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telebytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(regdatumbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rasbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rastext1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(antaltxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updbytebtn)
                                .addGap(18, 18, 18)))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel24)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminuppdateratillbakatbn)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regdatumbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namnbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(losenordbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platsbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telebytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rastext1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antaltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rasbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updbytebtn)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updbytebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbytebtnActionPerformed

        try {
            String sql = "UPDATE alien SET Namn=?, Registreringsdatum=?, Losenord=?, Ansvarig_Agent=?, Plats=?, Telefon=? WHERE Alien_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, Namnbytetxt.getText());
            pst.setString(2, regdatumbytetxt.getText());
            pst.setString(3, losenordbytetxt.getText());
            pst.setString(4, ansbytetxt.getText());
            pst.setString(5, platsbytetxt.getText());
            pst.setString(6, telebytetxt.getText());
            pst.setString(7, alienbytetxt.getText());
            if (rasbox1.getSelectedItem().equals("Boglodite")) {
                String boglodite = "UPDATE boglodite SET Antal_Boogies=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(boglodite);
                pst.setString(1, antaltxt1.getText());
                pst.setString(2, alienbytetxt.getText());
            }
            else if(rasbox1.getSelectedItem().equals("Squid"))
            {
                String squid = "UPDATE squid SET Antal_Armar=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(squid);
                pst.setString(1, antaltxt1.getText());
                pst.setString(2, alienbytetxt.getText());
            }
            /*else if(rasbox.getSelectedItem().equals("Worm"))
            {
                String squid = "UPDATE worm SET Antal_Worms=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(squid);
                pst.setString(1, antaltxt.getText());
                pst.setString(2, alienbytetxt.getText());
            }*/
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Uppdaterad alien");
            AdminAlienInfo meny = new AdminAlienInfo();
            meny.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updbytebtnActionPerformed

    private void NamnbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamnbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamnbytetxtActionPerformed

    private void adminuppdateratillbakatbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuppdateratillbakatbnActionPerformed
        AdminAlienInfo meny = new AdminAlienInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminuppdateratillbakatbnActionPerformed

    private void regdatumbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdatumbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regdatumbytetxtActionPerformed

    private void rasbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasbox1ActionPerformed
        if (rasbox1.getSelectedItem().equals("Boglodite")) {
            rastext1.setText("Antal boogies:");
        }
        else if(rasbox1.getSelectedItem().equals("Squid")){
            rastext1.setText("Antal armar:");
        }
        else if(rasbox1.getSelectedItem().equals("Worm")){
            rastext1.setText("Antal ?:");
        }
    }//GEN-LAST:event_rasbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUppdateraAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Namnbytetxt;
    private javax.swing.JButton adminuppdateratillbakatbn;
    private javax.swing.JTextField alienbytetxt;
    private javax.swing.JTextField ansbytetxt;
    private javax.swing.JTextField antaltxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JTextField losenordbytetxt;
    private javax.swing.JTextField platsbytetxt;
    private javax.swing.JComboBox<String> rasbox1;
    private javax.swing.JLabel rastext1;
    private javax.swing.JTextField regdatumbytetxt;
    private javax.swing.JTextField telebytetxt;
    private javax.swing.JLabel txt;
    private javax.swing.JButton updbytebtn;
    // End of variables declaration//GEN-END:variables
}
