/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class AdminTaBortUtrustning extends javax.swing.JFrame {

    /**
     * Creates new form AdminTaBortUtrustning
     */
    public AdminTaBortUtrustning() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admindeleteutrustningtillbakabtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vapenidtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teknikidtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kommunikationidtxt = new javax.swing.JTextField();
        raderavapenbtn = new javax.swing.JButton();
        raderabtn = new javax.swing.JButton();
        raderakommunikatiobtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admindeleteutrustningtillbakabtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        admindeleteutrustningtillbakabtn.setText("Tillbaka");
        admindeleteutrustningtillbakabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admindeleteutrustningtillbakabtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ta bort utrustning");

        jLabel2.setText("Vapen ID");

        jLabel3.setText("Teknik ID");

        jLabel4.setText("Kommunikation ID");

        raderavapenbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raderavapenbtn.setText("Radera");
        raderavapenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raderavapenbtnActionPerformed(evt);
            }
        });

        raderabtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raderabtn.setText("Radera");
        raderabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raderabtnActionPerformed(evt);
            }
        });

        raderakommunikatiobtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raderakommunikatiobtn.setText("Radera");
        raderakommunikatiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raderakommunikatiobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vapenidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(teknikidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(raderavapenbtn)
                                            .addComponent(raderabtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kommunikationidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(raderakommunikatiobtn)))))
                        .addGap(0, 159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(admindeleteutrustningtillbakabtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admindeleteutrustningtillbakabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vapenidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raderavapenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teknikidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raderabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kommunikationidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raderakommunikatiobtn))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admindeleteutrustningtillbakabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admindeleteutrustningtillbakabtnActionPerformed
        AdminAgentInfo meny = new AdminAgentInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_admindeleteutrustningtillbakabtnActionPerformed

    private void raderavapenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raderavapenbtnActionPerformed
        try {
            String vapen = "DELETE FROM vapen WHERE Utrustnings_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(vapen);
            pst.setString(1, vapenidtxt.getText());
            pst.executeUpdate();
            String innehar = "DELETE FROM innehar_utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(innehar);
            pst.setString(1, vapenidtxt.getText());
            pst.executeUpdate();
            String utrustning = "DELETE FROM utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(utrustning);
            pst.setString(1, vapenidtxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Vapen borttagen!");
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_raderavapenbtnActionPerformed

    private void raderabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raderabtnActionPerformed
        try {
            String teknik = "DELETE FROM teknik WHERE Utrustnings_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(teknik);
            pst.setString(1, teknikidtxt.getText());
            pst.executeUpdate();
            String innehar = "DELETE FROM innehar_utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(innehar);
            pst.setString(1, teknikidtxt.getText());
            pst.executeUpdate();
            String utrustning = "DELETE FROM utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(utrustning);
            pst.setString(1, teknikidtxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Teknik borttagen!");
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_raderabtnActionPerformed

    private void raderakommunikatiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raderakommunikatiobtnActionPerformed
        try {
            String kommunikation = "DELETE FROM kommunikation WHERE Utrustnings_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(kommunikation);
            pst.setString(1, kommunikationidtxt.getText());
            pst.executeUpdate();
            String innehar = "DELETE FROM innehar_utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(innehar);
            pst.setString(1, kommunikationidtxt.getText());
            pst.executeUpdate();
            String utrustning = "DELETE FROM utrustning WHERE Utrustnings_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(utrustning);
            pst.setString(1, kommunikationidtxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Kommunikation borttagen!");
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_raderakommunikatiobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTaBortUtrustning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admindeleteutrustningtillbakabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField kommunikationidtxt;
    private javax.swing.JButton raderabtn;
    private javax.swing.JButton raderakommunikatiobtn;
    private javax.swing.JButton raderavapenbtn;
    private javax.swing.JTextField teknikidtxt;
    private javax.swing.JTextField vapenidtxt;
    // End of variables declaration//GEN-END:variables
}
