/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

/**
 *
 * @author Pc
 */
public class AdminAlienInfo extends javax.swing.JFrame {

    /**
     * Creates new form AdminAlienInfo
     */
    public AdminAlienInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminuppdateraalienbtn = new javax.swing.JButton();
        admindeletealienbtn = new javax.swing.JButton();
        adminnyregalien = new javax.swing.JButton();
        Adminalienavslutabtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminuppdateraalienbtn.setText("Uppdatera alien");
        adminuppdateraalienbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuppdateraalienbtnActionPerformed(evt);
            }
        });

        admindeletealienbtn.setText("Ta bort alien");
        admindeletealienbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admindeletealienbtnActionPerformed(evt);
            }
        });

        adminnyregalien.setText("Nyregistrera alien");
        adminnyregalien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminnyregalienActionPerformed(evt);
            }
        });

        Adminalienavslutabtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Adminalienavslutabtn.setText("Avsluta");
        Adminalienavslutabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminalienavslutabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(Adminalienavslutabtn)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(137, 137, 137)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(adminnyregalien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminuppdateraalienbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admindeletealienbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(144, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Adminalienavslutabtn)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(adminnyregalien)
                    .addGap(18, 18, 18)
                    .addComponent(adminuppdateraalienbtn)
                    .addGap(18, 18, 18)
                    .addComponent(admindeletealienbtn)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminuppdateraalienbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuppdateraalienbtnActionPerformed
        AdminUppdateraAlien meny = new AdminUppdateraAlien();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminuppdateraalienbtnActionPerformed

    private void admindeletealienbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admindeletealienbtnActionPerformed
        AdminTaBortAlien meny = new AdminTaBortAlien();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_admindeletealienbtnActionPerformed

    private void adminnyregalienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminnyregalienActionPerformed
        AdminNyregistreraAlien meny = new AdminNyregistreraAlien();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminnyregalienActionPerformed

    private void AdminalienavslutabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminalienavslutabtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_AdminalienavslutabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAlienInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAlienInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adminalienavslutabtn;
    private javax.swing.JButton admindeletealienbtn;
    private javax.swing.JButton adminnyregalien;
    private javax.swing.JButton adminuppdateraalienbtn;
    // End of variables declaration//GEN-END:variables
}
