/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Pc
 */
public class AdminNyregistreraAgent extends javax.swing.JFrame {

    /**
     * Creates new form AdminNyregistreraAgent
     */
    public AdminNyregistreraAgent() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admindeleteutrustningtillbakabtn = new javax.swing.JButton();
        adminagentregbtn = new javax.swing.JButton();
        adminagentdatumtxt = new javax.swing.JTextField();
        adminagentomradetxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        adminagentlosentxt = new javax.swing.JTextField();
        adminagentteletxt = new javax.swing.JTextField();
        adminagentnamntxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        adminagentidtxt = new javax.swing.JTextField();
        adminregyesno = new javax.swing.JComboBox<>();
        yesnotxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admindeleteutrustningtillbakabtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        admindeleteutrustningtillbakabtn.setText("Tillbaka");
        admindeleteutrustningtillbakabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admindeleteutrustningtillbakabtnActionPerformed(evt);
            }
        });

        adminagentregbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminagentregbtn.setText("Registrera");
        adminagentregbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminagentregbtnActionPerformed(evt);
            }
        });

        adminagentdatumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminagentdatumtxtActionPerformed(evt);
            }
        });

        jLabel13.setText("Telefon");

        jLabel17.setText("Anstallningsdatum");

        jLabel15.setText("Namn");

        jLabel12.setText("Område*");

        adminagentlosentxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminagentlosentxtActionPerformed(evt);
            }
        });

        adminagentteletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminagentteletxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Lösenord*");

        jLabel44.setText("Agent ID");

        jLabel16.setText("Administrator");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Registrera ny agent");

        adminregyesno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Ja", "Nej" }));
        adminregyesno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminregyesnoActionPerformed(evt);
            }
        });

        yesnotxt.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        yesnotxt.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admindeleteutrustningtillbakabtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminagentnamntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminagentteletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adminregyesno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yesnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminagentdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(adminagentomradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(adminagentlosentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(adminagentregbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admindeleteutrustningtillbakabtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminagentnamntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminagentlosentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminagentomradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminagentteletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminagentdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yesnotxt)
                    .addComponent(adminregyesno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(adminagentregbtn)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admindeleteutrustningtillbakabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admindeleteutrustningtillbakabtnActionPerformed
        AdminAgentInfo meny = new AdminAgentInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_admindeleteutrustningtillbakabtnActionPerformed

    private void adminagentregbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminagentregbtnActionPerformed
        
        try {
            String sql = "INSERT INTO agent"
            + "(Agent_ID, Namn, Telefon, Anstallningsdatum, Administrator, Losenord, Omrade)"
            + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, adminagentidtxt.getText());
            pst.setString(2, adminagentnamntxt.getText());
            pst.setString(3, adminagentteletxt.getText());
            pst.setString(4, adminagentdatumtxt.getText());
            pst.setString(5, yesnotxt.getText());
            pst.setString(6, adminagentlosentxt.getText());
            pst.setString(7, adminagentomradetxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ny agent har registrerats!");
            adminagentidtxt.setText("");
            adminagentnamntxt.setText("");
            adminagentteletxt.setText("");
            adminagentdatumtxt.setText("");
            yesnotxt.setText("");
            adminagentlosentxt.setText("");
            adminagentomradetxt.setText("");
            adminregyesno.setSelectedItem("Välj");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adminagentregbtnActionPerformed

    private void adminagentdatumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminagentdatumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminagentdatumtxtActionPerformed

    private void adminagentlosentxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminagentlosentxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminagentlosentxtActionPerformed

    private void adminagentteletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminagentteletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminagentteletxtActionPerformed

    private void adminregyesnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminregyesnoActionPerformed
        if (adminregyesno.getSelectedItem().equals("Ja")) {
            yesnotxt.setText("J");
        }
        else if(adminregyesno.getSelectedItem().equals("Nej")){
            yesnotxt.setText("N");
        }
    }//GEN-LAST:event_adminregyesnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNyregistreraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNyregistreraAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminagentdatumtxt;
    private javax.swing.JTextField adminagentidtxt;
    private javax.swing.JTextField adminagentlosentxt;
    private javax.swing.JTextField adminagentnamntxt;
    private javax.swing.JTextField adminagentomradetxt;
    private javax.swing.JButton adminagentregbtn;
    private javax.swing.JTextField adminagentteletxt;
    private javax.swing.JButton admindeleteutrustningtillbakabtn;
    private javax.swing.JComboBox<String> adminregyesno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel yesnotxt;
    // End of variables declaration//GEN-END:variables
}
