/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib_start;

import mib_admin.AdminAgentInfo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Pc
 */
public class AdminUppdateraAgent extends javax.swing.JFrame {

    /**
     * Creates new form AdminUppdateraAgent
     */
    public AdminUppdateraAgent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminuppdateratillbakatbtn1 = new javax.swing.JButton();
        adminupdidtxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        adminupdagentlosentxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        adminupdagentomradetxt = new javax.swing.JTextField();
        adminupdteletxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        adminupdansdatumtxt = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        janejbox = new javax.swing.JComboBox<>();
        adminupdnamntxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        updbytebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        janejtxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminuppdateratillbakatbtn1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        adminuppdateratillbakatbtn1.setText("Tillbaka");
        adminuppdateratillbakatbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminuppdateratillbakatbtn1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Agent ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Uppdatera agent");

        jLabel23.setText("Lösenord:");

        jLabel22.setText("Administrator:");

        txt.setText("Telefon:");

        jLabel21.setText("Anställningsdatum:");

        janejbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj", "Ja", "Nej" }));
        janejbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                janejboxActionPerformed(evt);
            }
        });

        adminupdnamntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminupdnamntxtActionPerformed(evt);
            }
        });

        jLabel20.setText("Namn:");

        updbytebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updbytebtn.setText("Uppdatera");
        updbytebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbytebtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Områdes ID:");

        janejtxt.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminuppdateratillbakatbtn1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminupdnamntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminupdteletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminupdansdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminupdidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminupdagentlosentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel1)
                            .addComponent(jLabel22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updbytebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adminupdagentomradetxt, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(janejbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(janejtxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminuppdateratillbakatbtn1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdnamntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdteletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdansdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(janejbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(janejtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdagentlosentxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminupdagentomradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updbytebtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminuppdateratillbakatbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminuppdateratillbakatbtn1ActionPerformed
        AdminAgentInfo meny = new AdminAgentInfo();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_adminuppdateratillbakatbtn1ActionPerformed

    private void janejboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_janejboxActionPerformed
        if (janejbox.getSelectedItem().equals("Ja")) {
            janejtxt.setText("J");
        }
        else if(janejbox.getSelectedItem().equals("Nej")){
            janejtxt.setText("N");
        }
    }//GEN-LAST:event_janejboxActionPerformed

    private void adminupdnamntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminupdnamntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminupdnamntxtActionPerformed

    private void updbytebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbytebtnActionPerformed
        try {
            String sql = "UPDATE agent SET Namn=?, Telefon=?, Anstallningsdatum=?, Administrator=?, losenord=?, Omrade=? WHERE Agent_ID=?";
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, adminupdnamntxt.getText());
            pst.setString(2, adminupdteletxt.getText());
            pst.setString(3, adminupdansdatumtxt.getText());
            pst.setString(4, janejtxt.getText());
            pst.setString(5, adminupdagentlosentxt.getText());
            pst.setString(6, adminupdagentomradetxt.getText());
            pst.setString(7, adminupdidtxt.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Uppdaterad agent");
            AdminAgentInfo meny = new AdminAgentInfo();
            meny.setVisible(true);
            setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updbytebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUppdateraAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUppdateraAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminupdagentlosentxt;
    private javax.swing.JTextField adminupdagentomradetxt;
    private javax.swing.JTextField adminupdansdatumtxt;
    private javax.swing.JTextField adminupdidtxt;
    private javax.swing.JTextField adminupdnamntxt;
    private javax.swing.JTextField adminupdteletxt;
    private javax.swing.JButton adminuppdateratillbakatbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JComboBox<String> janejbox;
    private javax.swing.JLabel janejtxt;
    private javax.swing.JLabel txt;
    private javax.swing.JButton updbytebtn;
    // End of variables declaration//GEN-END:variables
}
