/*
 * To change this license header, chooimport java.sql.DriverManager;se License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib_start;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;

/**
 *
 * @author Pc
 */
public class AgentHuvudMeny extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement awp = null;
    ResultSet rs = null;
    private static InfDB idb;
    
    public AgentHuvudMeny() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idb = idb;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        rasgrupp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bytlosenbtn = new javax.swing.JButton();
        AgentIDlosbyt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nyttlostxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        namnutrustningtxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        utrustningidtxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        kalibertxt = new javax.swing.JTextField();
        vapenlaggtillbtn = new javax.swing.JButton();
        utrustningidtxt2 = new javax.swing.JTextField();
        namnutrustningtxt2 = new javax.swing.JTextField();
        overfortxt = new javax.swing.JTextField();
        kommunikationlaggtillbtn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        utrustningidtxt3 = new javax.swing.JTextField();
        namnutrustningtxt3 = new javax.swing.JTextField();
        kraftkallatxt = new javax.swing.JTextField();
        tekniklaggtillbtn = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        vapenagentidtxt = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        vapendatumtxt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        kommunikationdatumtxt = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        kommunikationagentidtxt = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        teknikdatumtxt = new javax.swing.JTextField();
        teknikagentidtxt = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane55 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        infoaidtxt = new javax.swing.JTextField();
        hamtadatabtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        infoalientable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        namntxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        telefontxt = new javax.swing.JTextField();
        laggtillbtn = new javax.swing.JButton();
        regdatumtxt = new javax.swing.JTextField();
        platstxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ansvarigtxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        losenordtxt = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        regalienidtxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Namnbytetxt = new javax.swing.JTextField();
        txt = new javax.swing.JLabel();
        losenordbytetxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ansbytetxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        platsbytetxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        telebytetxt = new javax.swing.JTextField();
        updbytebtn = new javax.swing.JButton();
        alienbytetxt = new javax.swing.JTextField();
        updregdatumtxt = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        rasbox = new javax.swing.JComboBox<>();
        antaltxt = new javax.swing.JTextField();
        rastext = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        sveabtn = new javax.swing.JButton();
        gotbtn = new javax.swing.JButton();
        norrbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        platstable = new javax.swing.JTable();
        jLabel43 = new javax.swing.JLabel();
        omcheftxt = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        squidtxt = new javax.swing.JButton();
        bogloditetxt = new javax.swing.JButton();
        wormtxt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rastable = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        frandatumtxt = new javax.swing.JTextField();
        tilldatumtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        datumtable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jButton2.setText("jButton2");

        jLabel18.setText("jLabel18");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setText("MIB Agent");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        bytlosenbtn.setText("Byt löenord");
        bytlosenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bytlosenbtnActionPerformed(evt);
            }
        });

        AgentIDlosbyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentIDlosbytActionPerformed(evt);
            }
        });

        jLabel6.setText("AgentID:");

        jLabel5.setText("Nytt lösenord:");

        nyttlostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttlostxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nyttlostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bytlosenbtn))
                    .addComponent(AgentIDlosbyt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AgentIDlosbyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyttlostxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bytlosenbtn)
                    .addComponent(jLabel5))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Ändra mitt lösenord", jPanel1);

        jLabel24.setText("Vapen");

        jLabel25.setText("Kommunikation:");

        jLabel26.setText("Teknik:");

        jLabel27.setText("Namn på utrustning:");

        jLabel28.setText("ID för utrustning: ");

        jLabel29.setText("Kaliber:");

        kalibertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalibertxtActionPerformed(evt);
            }
        });

        vapenlaggtillbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vapenlaggtillbtn.setText("Lägg till");
        vapenlaggtillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vapenlaggtillbtnActionPerformed(evt);
            }
        });

        utrustningidtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrustningidtxt2ActionPerformed(evt);
            }
        });

        kommunikationlaggtillbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kommunikationlaggtillbtn.setText("Lägg till");
        kommunikationlaggtillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kommunikationlaggtillbtnActionPerformed(evt);
            }
        });

        jLabel30.setText("ID för utrustning: ");

        jLabel31.setText("Namn på utrustning:");

        jLabel32.setText("Kraftkälla:");

        jLabel33.setText("ID för utrustning: ");

        jLabel34.setText("Namn på utrustning:");

        jLabel35.setText("Överföringsteknik:");

        utrustningidtxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrustningidtxt3ActionPerformed(evt);
            }
        });

        namnutrustningtxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnutrustningtxt3ActionPerformed(evt);
            }
        });

        tekniklaggtillbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tekniklaggtillbtn.setText("Lägg till");
        tekniklaggtillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekniklaggtillbtnActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel47.setText("Nyregistrering av utrustning");

        jLabel37.setText("Agent ID:");

        jLabel38.setText("Utkvitterings datum:");

        jLabel39.setText("Utkvitterings datum:");

        jLabel40.setText("Agent ID:");

        jLabel41.setText("Utkvitterings datum:");

        jLabel42.setText("Agent ID:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel47))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(kommunikationagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(utrustningidtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(namnutrustningtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(overfortxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(vapenagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel28)
                                    .addComponent(utrustningidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(namnutrustningtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(kalibertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addComponent(teknikagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addComponent(utrustningidtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(namnutrustningtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(kraftkallatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(teknikdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(vapendatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(kommunikationdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tekniklaggtillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vapenlaggtillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kommunikationlaggtillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel47)
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vapenagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(utrustningidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namnutrustningtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kalibertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(vapenlaggtillbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vapendatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kommunikationlaggtillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel30)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(utrustningidtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(namnutrustningtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kommunikationagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(overfortxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kommunikationdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel34)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(namnutrustningtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jLabel26))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kraftkallatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(teknikdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel33)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(utrustningidtxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel42)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(teknikagentidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tekniklaggtillbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Utrustning", jPanel5);

        jTabbedPane1.addTab("Meny", jTabbedPane3);

        jLabel36.setText("Alien ID");

        hamtadatabtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hamtadatabtn.setText("Hämta data");
        hamtadatabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamtadatabtnActionPerformed(evt);
            }
        });

        infoalientable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registreringsdatum", "Lösenord", "Namn", "Telefon", "Plats", "Ansvarig Agent"
            }
        ));
        jScrollPane4.setViewportView(infoalientable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hamtadatabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoaidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hamtadatabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );

        jTabbedPane55.addTab("Info", jPanel2);

        jLabel14.setText("Lösenord*");

        jLabel15.setText("Namn");

        jLabel16.setText("Telefonnummer");

        laggtillbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        laggtillbtn.setText("Registrera");
        laggtillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laggtillbtnActionPerformed(evt);
            }
        });

        regdatumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdatumtxtActionPerformed(evt);
            }
        });

        jLabel17.setText("Datum tillagd");

        jLabel12.setText("Plats ID*");

        ansvarigtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansvarigtxtActionPerformed(evt);
            }
        });

        jLabel13.setText("Ansvarig agent*");

        losenordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenordtxtActionPerformed(evt);
            }
        });

        jLabel44.setText("Alien ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ansvarigtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefontxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel12)
                                    .addComponent(platstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(losenordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(laggtillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regalienidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regalienidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(losenordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansvarigtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(laggtillbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane55.addTab("Nyregistrera alien", jPanel6);

        jLabel19.setText("Alien ID");

        jLabel20.setText("Namn:");

        Namnbytetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamnbytetxtActionPerformed(evt);
            }
        });

        txt.setText("Lösenord:");

        jLabel21.setText("Ansvarig agent:");

        jLabel22.setText("Plats ID:");

        jLabel23.setText("Telefonnummer:");

        updbytebtn.setText("Uppdatera");
        updbytebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbytebtnActionPerformed(evt);
            }
        });

        updregdatumtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updregdatumtxtActionPerformed(evt);
            }
        });

        jLabel48.setText("Registreringsdatum:");

        rasbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj ras", "Boglodite", "Squid", "Worm" }));
        rasbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rasboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(rasbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Namnbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(ansbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(platsbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(updregdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(txt)
                    .addComponent(losenordbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telebytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rastext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(antaltxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updbytebtn)
                .addGap(334, 334, 334))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alienbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updregdatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Namnbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(losenordbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ansbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(platsbytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telebytetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rastext, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(antaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rasbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updbytebtn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane55.addTab("Uppdatera befintlig alien", jPanel4);

        sveabtn.setText("Svealand");
        sveabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sveabtnActionPerformed(evt);
            }
        });

        gotbtn.setText("Götaland");
        gotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotbtnActionPerformed(evt);
            }
        });

        norrbtn.setText("Norrland");
        norrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norrbtnActionPerformed(evt);
            }
        });

        platstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alien ID", "Namn", "Ort"
            }
        ));
        jScrollPane1.setViewportView(platstable);

        jLabel43.setText("Områdes chef:");

        omcheftxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gotbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(norrbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sveabtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(omcheftxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(sveabtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gotbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(norrbtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(omcheftxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane55.addTab("Plats", jPanel7);

        squidtxt.setText("Squid");
        squidtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squidtxtActionPerformed(evt);
            }
        });

        bogloditetxt.setText("Boglodite");
        bogloditetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bogloditetxtActionPerformed(evt);
            }
        });

        wormtxt.setText("Worm");
        wormtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wormtxtActionPerformed(evt);
            }
        });

        rastable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alien ID", "Namn"
            }
        ));
        jScrollPane2.setViewportView(rastable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bogloditetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(squidtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wormtxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(squidtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bogloditetxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wormtxt))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane55.addTab("Ras", jPanel8);

        jLabel45.setText("Från:");

        jLabel46.setText("Till:");

        jButton1.setText("Hämta data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        datumtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alien ID", "Namn"
            }
        ));
        jScrollPane3.setViewportView(datumtable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tilldatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frandatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel45)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frandatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tilldatumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane55.addTab("Registreringsdatum", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane55)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane55)
        );

        jTabbedPane1.addTab("Alien", jPanel3);

        jButton3.setText("Logga ut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Admin");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updbytebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbytebtnActionPerformed

        try {
            String sql = "UPDATE alien SET Namn=?, Registreringsdatum=?, Losenord=?, Ansvarig_Agent=?, Plats=?, Telefon=? WHERE Alien_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, Namnbytetxt.getText());
            pst.setString(2, updregdatumtxt.getText());
            pst.setString(3, losenordbytetxt.getText());
            pst.setString(4, ansbytetxt.getText());
            pst.setString(5, platsbytetxt.getText());
            pst.setString(6, telebytetxt.getText());
            pst.setString(7, alienbytetxt.getText());
            if (rasbox.getSelectedItem().equals("Boglodite")) {
                String boglodite = "UPDATE boglodite SET Antal_Boogies=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(boglodite);
                pst.setString(1, antaltxt.getText());
                pst.setString(2, alienbytetxt.getText());
            }
            else if(rasbox.getSelectedItem().equals("Squid"))
            {
                String squid = "UPDATE squid SET Antal_Armar=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(squid);
                pst.setString(1, antaltxt.getText());
                pst.setString(2, alienbytetxt.getText());
            }
            /*else if(rasbox.getSelectedItem().equals("Worm"))
            {
                String squid = "UPDATE worm SET Antal_Worms=? WHERE Alien_ID=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
                pst = con.prepareStatement(squid);
                pst.setString(1, antaltxt.getText());
                pst.setString(2, alienbytetxt.getText());
            }*/
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Uppdaterad alien");
            Namnbytetxt.setText("");
            updregdatumtxt.setText("");
            losenordbytetxt.setText("");
            ansbytetxt.setText("");
            platsbytetxt.setText("");
            telebytetxt.setText("");
            alienbytetxt.setText("");
            antaltxt.setText("");
            rasbox.setSelectedItem("Välj ras");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updbytebtnActionPerformed

    private void NamnbytetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamnbytetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamnbytetxtActionPerformed

    private void losenordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenordtxtActionPerformed

    private void ansvarigtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansvarigtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansvarigtxtActionPerformed

    private void regdatumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdatumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regdatumtxtActionPerformed

    private void laggtillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laggtillbtnActionPerformed
        try {
            String sql = "INSERT INTO alien"
            + "(Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_Agent)"
            + "VALUES (?, ?, ?, ?, ?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, regalienidtxt.getText());
            pst.setString(2, regdatumtxt.getText());
            pst.setString(3, losenordtxt.getText());
            pst.setString(4, namntxt.getText());
            pst.setString(5, telefontxt.getText());
            pst.setString(6, platstxt.getText());
            pst.setString(7, ansvarigtxt.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ny alien har registrerats!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_laggtillbtnActionPerformed

    private void hamtadatabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamtadatabtnActionPerformed
        infoalientable.setModel(new DefaultTableModel(null, new String[]{"Registreringsdatum", "Losenord","Namn", "Telefon","Plats", "Ansvarig_Agent"}));
        try {
            String sql = "SELECT alien.registreringsdatum, alien.losenord, alien.namn, alien.telefon, plats.Benamning, agent.Namn FROM alien JOIN plats ON alien.Plats = plats.Plats_ID JOIN agent ON alien.Ansvarig_Agent = agent.Agent_ID WHERE alien.Alien_ID=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, infoaidtxt.getText());
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String reg = rs.getString("Registreringsdatum");
                String losenord = rs.getString("Losenord");
                String namn = rs.getString("alien.Namn");
                String telefon = rs.getString("Telefon");
                String plats = rs.getString("plats.Benamning");
                String ansagent = rs.getString("agent.Namn");
                
                
                String tbData[] = {reg, losenord, namn, telefon, plats, ansagent};
                DefaultTableModel tblModel = (DefaultTableModel)infoalientable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_hamtadatabtnActionPerformed

    private void sveabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sveabtnActionPerformed
        
        platstable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn", "Benamning"}));
        try {
            String sql = "SELECT alien.Alien_ID, alien.Namn, plats.Benamning FROM alien JOIN plats ON alien.Plats = plats.Plats_ID JOIN omrade ON omrade.Omrades_ID = plats.Finns_I WHERE Omrades_ID=1";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                String benamning = rs.getString("Benamning");
                
                String tbData[] = {id, namn, benamning};
                DefaultTableModel tblModel = (DefaultTableModel)platstable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        try {
            String sql ="SELECT Namn FROM agent a INNER JOIN omradeschef o ON a.Agent_ID = o.Agent_ID WHERE a.Omrade=1";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while (rs.next()) {
                omcheftxt.setText(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_sveabtnActionPerformed

    private void gotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotbtnActionPerformed
        
        platstable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn", "Benamning"}));
        try {
            String sql = "SELECT alien.Alien_ID, alien.Namn, plats.Benamning FROM alien JOIN plats ON alien.Plats = plats.Plats_ID JOIN omrade ON omrade.Omrades_ID = plats.Finns_I WHERE Omrades_ID=2";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                String benamning = rs.getString("Benamning");
                
                String tbData[] = {id, namn, benamning};
                DefaultTableModel tblModel = (DefaultTableModel)platstable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        try {
            String sql ="SELECT Namn FROM agent a INNER JOIN omradeschef o ON a.Agent_ID = o.Agent_ID WHERE a.Omrade=2";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while (rs.next()) {
                omcheftxt.setText(rs.getString(1));
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_gotbtnActionPerformed

    private void norrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norrbtnActionPerformed
        
        platstable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn", "Benamning"}));
        try {
            String sql = "SELECT alien.Alien_ID, alien.Namn, plats.Benamning FROM alien JOIN plats ON alien.Plats = plats.Plats_ID JOIN omrade ON omrade.Omrades_ID = plats.Finns_I WHERE Omrades_ID=4";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                String benamning = rs.getString("Benamning");
                
                String tbData[] = {id, namn, benamning};
                DefaultTableModel tblModel = (DefaultTableModel)platstable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        try {
            String sql ="SELECT Namn FROM agent a INNER JOIN omradeschef o ON a.Agent_ID = o.Agent_ID WHERE a.Omrade=4";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while (rs.next()) {
                omcheftxt.setText(rs.getString(1));
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_norrbtnActionPerformed

    private void wormtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wormtxtActionPerformed
        rastable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn"}));
        try {
            String sql = "SELECT * FROM alien INNER JOIN worm ON alien.Alien_ID = worm.Alien_ID WHERE alien.Alien_ID=worm.Alien_ID";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                
                String tbData[] = {id, namn};
                DefaultTableModel tblModel = (DefaultTableModel)rastable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_wormtxtActionPerformed

    private void bogloditetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bogloditetxtActionPerformed
        rastable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn"}));
        try {
            String sql = "SELECT * FROM alien INNER JOIN boglodite ON alien.Alien_ID = boglodite.Alien_ID WHERE alien.Alien_ID=boglodite.Alien_ID";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                
                String tbData[] = {id, namn};
                DefaultTableModel tblModel = (DefaultTableModel)rastable.getModel();
                
                tblModel.addRow(tbData);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bogloditetxtActionPerformed

    private void squidtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squidtxtActionPerformed
        rastable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn"}));
        try {
            String sql = "SELECT * FROM alien INNER JOIN squid ON alien.Alien_ID = squid.Alien_ID WHERE alien.Alien_ID=squid.Alien_ID";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                
                String tbData[] = {id, namn};
                DefaultTableModel tblModel = (DefaultTableModel)rastable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_squidtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        datumtable.setModel(new DefaultTableModel(null, new String[]{"Alien_ID", "Namn"}));
        try {
            String sql = "SELECT Alien_ID, Namn FROM alien WHERE Registreringsdatum BETWEEN ? AND ?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, frandatumtxt.getText());
                pst.setString(2, tilldatumtxt.getText());
            ResultSet rs=pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("Alien_ID"));
                String namn = rs.getString("Namn");
                
                String tbData[] = {id, namn};
                DefaultTableModel tblModel = (DefaultTableModel)datumtable.getModel();
                
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AgentAlien meny = new AgentAlien();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tekniklaggtillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekniklaggtillbtnActionPerformed
        try {
            String sql = "INSERT INTO utrustning (Utrustnings_ID, Benamning) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, utrustningidtxt3.getText());
            pst.setString(2, namnutrustningtxt3.getText());
            pst.executeUpdate();
            pst.close();
            String sql2 = "INSERT INTO teknik (Utrustnings_ID, Kraftkalla) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql2);
            pst.setString(1, utrustningidtxt3.getText());
            pst.setString(2, kraftkallatxt.getText());
            pst.executeUpdate();
            pst.close();
            String sql3 = "INSERT INTO innehar_utrustning(Agent_ID, Utrustnings_ID, Utkvitteringsdatum) values (?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql3);
            pst.setString(1, teknikagentidtxt.getText());
            pst.setString(2, utrustningidtxt3.getText());
            pst.setString(3, teknikdatumtxt.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Ny teknik har registrerats!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tekniklaggtillbtnActionPerformed

    private void namnutrustningtxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnutrustningtxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnutrustningtxt3ActionPerformed

    private void utrustningidtxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrustningidtxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utrustningidtxt3ActionPerformed

    private void kommunikationlaggtillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kommunikationlaggtillbtnActionPerformed
        try {
            String sql = "INSERT INTO utrustning (Utrustnings_ID, Benamning) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, utrustningidtxt2.getText());
            pst.setString(2, namnutrustningtxt2.getText());
            pst.executeUpdate();
            pst.close();
            String sql2 = "INSERT INTO kommunikation (Utrustnings_ID, Overforingsteknik) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql2);
            pst.setString(1, utrustningidtxt2.getText());
            pst.setString(2, overfortxt.getText());
            pst.executeUpdate();
            pst.close();
            String sql3 = "INSERT INTO innehar_utrustning(Agent_ID, Utrustnings_ID, Utkvitteringsdatum) values (?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql3);
            pst.setString(1, kommunikationagentidtxt.getText());
            pst.setString(2, utrustningidtxt2.getText());
            pst.setString(3, kommunikationdatumtxt.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Ny kommunikation har registrerats!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_kommunikationlaggtillbtnActionPerformed

    private void utrustningidtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrustningidtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utrustningidtxt2ActionPerformed

    private void vapenlaggtillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vapenlaggtillbtnActionPerformed
        try {
            String sql = "INSERT INTO utrustning (Utrustnings_ID, Benamning) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql);
            pst.setString(1, utrustningidtxt.getText());
            pst.setString(2, namnutrustningtxt.getText());
            pst.executeUpdate();
            pst.close();
            String sql2 = "INSERT INTO vapen (Utrustnings_ID, Kaliber) VALUES (?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql2);
            pst.setString(1, utrustningidtxt.getText());
            pst.setString(2, kalibertxt.getText());
            pst.executeUpdate();
            pst.close();
            String sql3 = "INSERT INTO innehar_utrustning(Agent_ID, Utrustnings_ID, Utkvitteringsdatum) values (?, ?, ?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sql3);
            pst.setString(1, vapenagentidtxt.getText());
            pst.setString(2, utrustningidtxt.getText());
            pst.setString(3, vapendatumtxt.getText());
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Nytt vapen har registrerats!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        /*try {

            String sqlinsert = "INSERT INTO utrustning AS u (Utrustnings_ID, Benamning, Kaliber)"
            + "SELECT u.Utrustnings_ID, u.Utrustnings_ID FROM vapen AS v INNER JOIN u ON o.Utrustnings_ID = v.Utrustnings_ID";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            pst = con.prepareStatement(sqlinsert);
            pst.setString(1, utrustningidtxt.getText());
            pst.setString(2, namnutrustningtxt.getText());
            pst.setString(3, kalibertxt.getText());
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Nytt vapen har registrerats!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/

    }//GEN-LAST:event_vapenlaggtillbtnActionPerformed

    private void kalibertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalibertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalibertxtActionPerformed

    private void nyttlostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttlostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyttlostxtActionPerformed

    private void AgentIDlosbytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentIDlosbytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgentIDlosbytActionPerformed

    private void bytlosenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bytlosenbtnActionPerformed

        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb","mibdba","mibkey");
            PreparedStatement ps = connection.prepareStatement("UPDATE agent set Losenord=? where Agent_ID=? AND Administrator='N'");
            ps.setString(1, nyttlostxt.getText());
            ps.setString(2, AgentIDlosbyt.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Lösenord uppdaterad!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "AgentID existerar ej.");
        }
    }//GEN-LAST:event_bytlosenbtnActionPerformed

    private void updregdatumtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updregdatumtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updregdatumtxtActionPerformed

    private void rasboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rasboxActionPerformed
        if (rasbox.getSelectedItem().equals("Boglodite")) {
            rastext.setText("Antal boogies:");
        }
        else if(rasbox.getSelectedItem().equals("Squid")){
            rastext.setText("Antal armar:");
        }
        else if(rasbox.getSelectedItem().equals("Worm")){
            rastext.setText("Antal ?:");
        }
    }//GEN-LAST:event_rasboxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AgentLoggaInAdmin meny = new AgentLoggaInAdmin();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentHuvudMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentHuvudMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgentIDlosbyt;
    private javax.swing.JTextField Namnbytetxt;
    private javax.swing.JTextField alienbytetxt;
    private javax.swing.JTextField ansbytetxt;
    private javax.swing.JTextField ansvarigtxt;
    private javax.swing.JTextField antaltxt;
    private javax.swing.JButton bogloditetxt;
    private javax.swing.JButton bytlosenbtn;
    private javax.swing.JTable datumtable;
    private javax.swing.JTextField frandatumtxt;
    private javax.swing.JButton gotbtn;
    private javax.swing.JButton hamtadatabtn;
    private javax.swing.JTextField infoaidtxt;
    private javax.swing.JTable infoalientable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane55;
    private javax.swing.JTextField kalibertxt;
    private javax.swing.JTextField kommunikationagentidtxt;
    private javax.swing.JTextField kommunikationdatumtxt;
    private javax.swing.JButton kommunikationlaggtillbtn;
    private javax.swing.JTextField kraftkallatxt;
    private javax.swing.JButton laggtillbtn;
    private javax.swing.JTextField losenordbytetxt;
    private javax.swing.JTextField losenordtxt;
    private javax.swing.JTextField namntxt;
    private javax.swing.JTextField namnutrustningtxt;
    private javax.swing.JTextField namnutrustningtxt2;
    private javax.swing.JTextField namnutrustningtxt3;
    private javax.swing.JButton norrbtn;
    private javax.swing.JTextField nyttlostxt;
    private javax.swing.JLabel omcheftxt;
    private javax.swing.JTextField overfortxt;
    private javax.swing.JTextField platsbytetxt;
    private javax.swing.JTable platstable;
    private javax.swing.JTextField platstxt;
    private javax.swing.JComboBox<String> rasbox;
    private javax.swing.ButtonGroup rasgrupp;
    private javax.swing.JTable rastable;
    private javax.swing.JLabel rastext;
    private javax.swing.JTextField regalienidtxt;
    private javax.swing.JTextField regdatumtxt;
    private javax.swing.JButton squidtxt;
    private javax.swing.JButton sveabtn;
    private javax.swing.JTextField teknikagentidtxt;
    private javax.swing.JTextField teknikdatumtxt;
    private javax.swing.JButton tekniklaggtillbtn;
    private javax.swing.JTextField telebytetxt;
    private javax.swing.JTextField telefontxt;
    private javax.swing.JTextField tilldatumtxt;
    private javax.swing.JLabel txt;
    private javax.swing.JButton updbytebtn;
    private javax.swing.JTextField updregdatumtxt;
    private javax.swing.JTextField utrustningidtxt;
    private javax.swing.JTextField utrustningidtxt2;
    private javax.swing.JTextField utrustningidtxt3;
    private javax.swing.JTextField vapenagentidtxt;
    private javax.swing.JTextField vapendatumtxt;
    private javax.swing.JButton vapenlaggtillbtn;
    private javax.swing.JButton wormtxt;
    // End of variables declaration//GEN-END:variables
}
