/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib_start;

import mib_alien.AlienHuvudMeny;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import oru.inf.InfException;
import java.util.logging.Level;
import java.util.logging.Logger;
import mib_verktyg.Validering;

/**
 *
 * @author Pc
 */
public class AlienLoggaIn extends javax.swing.JFrame {

    /**
     * Creates new form AlienLoggaIn
     */
    public AlienLoggaIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        alienanvnamntxt = new javax.swing.JTextField();
        alienbackbtn = new javax.swing.JButton();
        alienloggainbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        alienlosenordtxt = new javax.swing.JPasswordField();
        alienresetbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Lösenord:");

        alienanvnamntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienanvnamntxtActionPerformed(evt);
            }
        });

        alienbackbtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        alienbackbtn.setText("Tillbaka");
        alienbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienbackbtnActionPerformed(evt);
            }
        });

        alienloggainbtn.setText("Logga in");
        alienloggainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienloggainbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pc\\Downloads\\fghjklö_ccexpress.png")); // NOI18N

        alienlosenordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienlosenordtxtActionPerformed(evt);
            }
        });
        alienlosenordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                alienlosenordtxtKeyReleased(evt);
            }
        });

        alienresetbtn.setText("Reset");
        alienresetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienresetbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Alien ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alienloggainbtn)
                    .addComponent(alienresetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alienlosenordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(alienanvnamntxt))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alienbackbtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alienbackbtn)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alienanvnamntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alienlosenordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alienloggainbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alienresetbtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alienanvnamntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienanvnamntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alienanvnamntxtActionPerformed

    private void alienbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienbackbtnActionPerformed
        AgentAlien meny = new AgentAlien();
        meny.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_alienbackbtnActionPerformed

    private void alienloggainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienloggainbtnActionPerformed
        Connection connection;
        PreparedStatement ps;
        if (Validering.textFaltHarVarde(alienanvnamntxt) && Validering.textFaltHarVarde(alienlosenordtxt) && Validering.isHeltal(alienanvnamntxt)) {
            try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mibdb", "mibdba", "mibkey");
                ps = connection.prepareStatement("Select * from alien where Alien_ID=? and Losenord=?");
                ps.setString(1, alienanvnamntxt.getText());
                ps.setString(2, alienlosenordtxt.getText());
                ResultSet result = ps.executeQuery();

                if (result.next()) {
                    JOptionPane.showMessageDialog(null, "Inloggningen lyckades.");
                    AlienHuvudMeny meny = new AlienHuvudMeny();
                    meny.setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Inloggningen misslyckades.");
                    alienanvnamntxt.setText("");
                    alienlosenordtxt.setText("");
                }
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, e);
            } catch (SQLException ex) {
                Logger.getLogger(AlienLoggaIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_alienloggainbtnActionPerformed

    private void alienlosenordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienlosenordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alienlosenordtxtActionPerformed

    private void alienresetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienresetbtnActionPerformed
        if (evt.getSource() == alienresetbtn) {
            alienanvnamntxt.setText("");
            alienlosenordtxt.setText("");
        }
    }//GEN-LAST:event_alienresetbtnActionPerformed

    private void alienlosenordtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alienlosenordtxtKeyReleased

    }//GEN-LAST:event_alienlosenordtxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienLoggaIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienLoggaIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienLoggaIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienLoggaIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlienLoggaIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alienanvnamntxt;
    private javax.swing.JButton alienbackbtn;
    private javax.swing.JButton alienloggainbtn;
    private javax.swing.JPasswordField alienlosenordtxt;
    private javax.swing.JButton alienresetbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
